config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "login" => "users/sessions#new", :as => :signin_user
    post "login" => "users/sessions#create", :as => :signin_user_create
    get "logout" => "users/sessions#destroy", :as => :signout_user
  end

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }
  resources :users

  root "home#index"

  get "markets" => "markets#index", as: :markets

  namespace :admin do
    root "trades#new"
    get 'settings' => 'configurations#edit', as: :settings
    patch 'update_setting' => 'configurations#update', as: :update_setting

    resources :trades do
      member do
        get :release
        patch :released
        get :status
        patch :change_status
      end
    end
    resources :dashboards, only: [:index]
    resources :users do
      member do
        get :status
        patch :change_status
        get :trades
        get :login_histories
      end
    end
    resources :stores
  end

  namespace :device do
    resources :stores, only: [:show] do
      member do
        get :buy
        post :buying
        get :store
        post :storing
        get :verify
        post :verifying
        get :charge
        post :charging
      end
    end
  end
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user_id, :usd_amount, :btc_amount, :phone_number, :wallet, :exchange_rate
  validates_numericality_of :usd_amount, :btc_amount
  
  validate :checking_minimum_and_maximum
  validate :checking_daily_deposit

  scope :today, -> {where(created_at: (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day))	}
  scope :trade_open, -> {where(status: 'trade_open')}
  scope :trade_expired, -> {where(status: 'trade_expired')}
  scope :withdraw_requested, -> {where(status: 'withdraw_requested')}
  scope :btc_sent, -> {where(status: 'btc_sent')}
  scope :buying_btc, -> {where(status: 'buying_btc')}
  scope :open_or_buying, -> {where("status = ? OR status = ?", 'trade_open', 'buying_btc')}

  attr_accessor :update_status

  def checking_minimum_and_maximum
    return if update_status
    if self.usd_amount.to_f < AppConfiguration.current_config.minimum_deposit
      self.errors.add(:usd_amount, "Minimum deposit is $#{AppConfiguration.current_config.minimum_deposit}")
    elsif self.usd_amount.to_f > AppConfiguration.current_config.maximum_deposit
      self.errors.add(:usd_amount, "Maximum deposit is $#{AppConfiguration.current_config.maximum_deposit}")    	
    end
  end

  def checking_daily_deposit
    return if update_status
    return if self.user.nil?
    daily = self.user.trades.today.sum(:usd_amount)
    if daily > AppConfiguration.current_config.maximum_daily_deposit
      self.errors.add(:daily_deposit, "Maximum daily deposit is $#{AppConfiguration.current_config.maximum_daily_deposit}")
    elsif (daily + usd_amount.to_f) > AppConfiguration.current_config.maximum_daily_deposit
      self.errors.add(:daily_deposit, "Today only have $#{AppConfiguration.current_config.maximum_daily_deposit - daily}")
    end
  end

  def self.states
    {
    	trade_open: "Trade Open",
    	trade_expired: "Trade Expired",
    	withdraw_requested: "Withdraw Requested",
    	btc_sent: "BTC sent",
    	buying_btc: "Buying BTC"
    }
  end

  def self.checking_trade
    Trade.trade_open.where("created_at <= ?", Time.zone.now).update_all(status: 'trade_expired')
  end
end

app/controllers/admin/trades_controller.rb
class Admin::TradesController < Admin::ApplicationController

  def index
    @trades = Trade.order(created_at: :desc)
    if params[:status].present?
      @trades = @trades.where(status: params[:status])
    end
    @trades = @trades.page(params[:page]).per(25)
  end

  def new
    @bitcoin_price = BitCoinPrice.new_price
    @trade = Trade.new
  end

  def create
    @bitcoin_price = BitCoinPrice.new_price
    phone_number = trade_params[:phone_number]
    if phone_number.present?
      user = User.find_or_initialize_by(phone_number: phone_number)
      user.email = trade_params[:email]
      user.username = trade_params[:username]
      user.save(validate: false)
    end

    @trade = if user
      Trade.new(trade_params.merge(user_id: user.id))
    else
      Trade.new(trade_params)
    end
    if @trade.save
      redirect_to new_admin_trade_path, notice: 'Trade successfully created, you can manage on trade menu'
    else
      render :new
    end
  end

  def release
    @trade = Trade.find_by_id(params[:id])
  end

  def released
    @trade = Trade.find_by_id(params[:id])
    @updated = @trade.update_attributes(status: 'btc_sent', update_status: true)
  end
  def status
    @trade = Trade.find_by_id(params[:id])
  end

  def change_status
    @trade = Trade.find_by_id(params[:id])
    @state = @trade.update_attributes(status: params[:trade][:status], update_status: true)
  end

  private
  def trade_params
    params[:trade][:phone_number] = params[:trade][:phone_number].gsub(")", '').gsub("(","").gsub("-",'') rescue ""
    params.require(:trade).permit(:usd_amount, :btc_amount, :phone_number, :wallet, :user_id, :username, :email, :exchange_rate)
  end
end

app/views/admin/trades/_link_status.html.erb
<%= link_to "javascript:void(0)", onclick: "openModalSmall('#{status_admin_trade_path(trade.id, popup: true)}')" do %>
  <span class="<%= get_trade_status(trade.status) %>"><%= trade.status.humanize %></span>
<% end %>
	

app/views/admin/trades/_trade_list.html.erb
<%- @trades.each do |trade| %>
<tr id="trade-<%= trade.id %>">
	<td><%= trade.id %></td>
	<td><%= trade.created_at %></td>
	<td><%= trade.phone_number %></td>
	<td><%= trade.username %></td>
	<td><%= trade.usd_amount %></td>
	<td><%= trade.btc_amount %></td>
	<td><%= trade.location_to_pay %></td>
  <td>
    <%= link_to "Check", "javascript:void(0)" %>
  </td>
	<td id="trade-<%= trade.id %>-status">
	  <%= render partial: 'admin/trades/link_status', locals: {trade: trade} %>
	</td>
	<%- if release %>
    <td>
      <%= link_to "release", "javascript:void(0)", onclick: "openModalSmall('#{release_admin_trade_path(trade, popup: true)}')" %>
    </td>
	<% end %>
</tr>
<% end %>
<tr>
	<td colspan="<%= release ? 10 : 9 %>"><%= paginate @trades %></td>
</tr>

app/views/admin/trades/_trades.html.erb
<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<td>ID</td>
				<td>Date</td>
				<td>Phone</td>
				<td>Username</td>
				<td>Amount USD</td>
				<td>Amount BTC</td>
				<td>Location To Pay</td>
				<td>Notes</td>
				<td>Status</td>
			  <%- if release %>
  				<td></td>
			  <% end %>
			</tr>
		</thead>
		<tbody>
			<%= render partial: "admin/trades/trade_list", locals: {release: release} %>
		</tbody>
	</table>
</div>

app/views/admin/trades/change_status.js.erb
$("#trade-<%= @trade.id %>-status").html("<%= escape_javascript(render partial: 'link_status', locals: {trade: @trade}) %>");
$("#window-modal-small").modal('hide');

app/views/admin/trades/index.html.erb
<h1>Trades</h1>
<hr/>
<ul class="nav nav-tabs">
	<li role="presentation" class="<%= 'active' if !params[:status].present? %>">
		<a href="/admin/trades">All (<%= Trade.count %>)</a>
	</li>
	<%- Trade.states.each do |key, val| %>
	<li role="" class="<%= 'active' if params[:status].eql?(key.to_s) %>">
		<a href="/admin/trades?status=<%= key.to_s %>"><%= key.to_s.humanize %> (<%= eval("Trade.#{key.to_s}.count") %>)</a>
	</li>
	<% end %>
</ul>
<%= render partial: "trades", locals: {release: false} %>

app/views/admin/trades/new.html.erb
<h2>Market Prices</h2>
<table class="table">
  <thead>
    <tr>
      <td>Bitfinex</td>
      <td>OkCoin</td>
      <td>Bitstamp</td>
      <td>CoinBase</td>
      <td>itBit</td>
      <td>Highest Price</td>
      <td>Include fee <%= AppConfiguration.current_config.fee_percent.to_f.scale_2 %>%</td>
      <td>Updated At</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="bitfinex">$<%= prices_json[:bitfinex] %></td>
      <td class="okcoin">$<%= prices_json[:okcoin] %></td>
      <td class="bitstamp">$<%= prices_json[:bitstamp] %></td>
      <td class="coinbase">$<%= prices_json[:coinbase] %></td>
      <td class="itbit">$<%= prices_json[:itbit] %></td>
      <td class="maxprice">$<%= prices_json[:maxprice] %></td>
      <td class="price">$<%= prices_json[:price] %></td>
      <td class="updated_at"><%= prices_json[:updated_at] %></td>
    </tr>
  </tbody>
</table>
<hr/>
<h1>New Trade</h1>
<h2>Price: <span id="price" data-price="<%= prices_json[:price] %>">$<%= prices_json[:price] %>/1BTC</span></h2>
<div class="col-md-8 no-padding">
	<%= form_for @trade, url: admin_trades_path, html: {novalidate: 'novalidate'} do |f| %>
	<% if @trade.errors.any? %>
	<div class="alert alert-danger">
		<strong>There are <%= pluralize(@trade.errors.count, " errors") %></strong>
		<ul>
			<% @trade.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="col-md-3">
		<div class="form-group">
			<%= f.label :usd_amount %>
			<%= f.number_field :usd_amount, class: 'form-control' %>
			<%= f.hidden_field :exchange_rate, value: prices_json[:price] %>
		</div>
	</div>
	<div class="exchange col-md-2 text-center">
    <i class="fa fa-random"></i>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<%= f.label :btc_amount %>
			<%= f.number_field :btc_amount, class: 'form-control' %>
		</div>
	</div>
	<div class="col-md-8">
		<div class="form-group">
			<%= f.label :phone_number %>
			<%= f.text_field :phone_number, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :wallet %>
			<%= f.text_field :wallet, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :username %>
			<%= f.text_field :username, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control' %>
		</div>
		<%= f.submit "Create trade", class: 'btn btn-primary' %>
	</div>
	<% end %>
</div>

app/views/admin/trades/release.html.erb
<h2 class="text-center">Release BTC</h2>
<h3 class="text-center">Please process it manually on local wallet system</h3>
<div class="text-center">
	<div class="col-md-12 release-box">
		<strong>Send (BTC amount)</strong>: 
		<div class="input-group">
			<input id="btc-amount" type="text" value="<%= @trade.usd_amount %>" class="form-control">
			<span class="input-group-addon">
				<a id="cp-btc-amount" data-clipboard-demo="" data-clipboard-target="#btc-amount">
					<i class="fa fa-copy"></i>
				</a>
			</span>
		</div>
		<br/>
		<br/>
		<strong>To wallet address</strong>: 
		<div class="input-group">
			<input id="wallet" type="text" value="<%= @trade.wallet %>" class="form-control">
			<span class="input-group-addon">
				<a id="cp-wallet" data-clipboard-demo="" data-clipboard-target="#wallet">
					<i class="fa fa-copy"></i>
				</a>
			</span>
		</div>
	</div>
	<%= form_for @trade, url: released_admin_trade_path(@trade), remote: true do |f| %>
	<%= f.button "Cancel", class: 'btn btn-danger', type: 'reset', onclick: "$('#window-modal-small').modal('hide');" %>
	<%= f.submit "Yes, confirm", class: 'btn btn-primary', data: {disable_with: 'releasing...'} %>
	<% end %>
</div>

app/views/admin/trades/released.js.erb
<%- if @updated %>
  $("#trade-<%= @trade.id %>").remove();
  $("#window-modal-small").modal('hide');
<% end %>

app/views/admin/trades/status.html.erb
<div class="popup-content">
	<div class="popup-body">
		<%= form_for @trade, url: change_status_admin_trade_path(@trade), method: :patch, remote: true do |f| %>
		<div class="form-group">
			<%= f.label :status %>
			<%= f.select :status, options_for_select(Trade.states.map{|x,v| [v, x]}, selected: f.object.status), {}, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit "Change", class: 'btn btn-primary', data: {disable_with: 'Changin...'} %>
		</div>
		<% end %>
	</div>
</div>