config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "login" => "users/sessions#new", :as => :signin_user
    post "login" => "users/sessions#create", :as => :signin_user_create
    get "logout" => "users/sessions#destroy", :as => :signout_user
  end

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }
  resources :users

  root "home#index"

  get "markets" => "markets#index", as: :markets

  namespace :admin do
    root "trades#new"
    get 'settings' => 'configurations#edit', as: :settings
    patch 'update_setting' => 'configurations#update', as: :update_setting

    resources :trades do
      member do
        get :release
        patch :released
        get :status
        patch :change_status
      end
    end
    resources :dashboards, only: [:index]
    resources :users do
      member do
        get :status
        patch :change_status
        get :trades
        get :login_histories
      end
    end
    resources :stores
  end

  namespace :device do
    resources :stores, only: [:show] do
      member do
        get :buy
        post :buying
        get :store
        post :storing
        get :verify
        post :verifying
        get :charge
        post :charging
      end
    end
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  extend FriendlyId
  require 'bcrypt'
  friendly_id :name, use: :slugged
  attr_accessor :password, :password_hash

  validates_presence_of :name
  validates_uniqueness_of :name, :slug
  validate :password_format

  before_save :encryption_password

  def password_format
    if !self.new_record? && !password.present?
      return
    end
    if self.new_record? && !password.present?
      self.errors.add :password, 'Cant be blank.'
    end
    unless password.numeric?
      self.errors.add :password, 'Only numeric allowed.'
    end
  end

  def encryption_password
    if !self.new_record? && !password.present?
      return
    end
    self.password_hash = self.password
  end

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

  def password_hash
    if self.encrypted_password
      BCrypt::Password.new(self.encrypted_password)
    end
  end

  def password_hash=(new_password)
    @password_hash = BCrypt::Password.create(new_password)
    self.encrypted_password = @password_hash
  end

  def authenticate(pass)
    self.password_hash == pass
  end

  def url
    host = if Rails.env.eql?('development')
      "http://localhost:3000/device/stores/#{self.friendly_id}"
    else
      "http://104.236.38.53/device/stores/#{self.friendly_id}"
    end
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::ApplicationController

  def index
    @stores = Store.order(:name).page(params[:page]).per(25)
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    @created = @store.save
    respond_to do |f|
      f.html{redirect_to new_admin_store_path}
      f.js{
        if @created
          flash.now[:notice] = 'Succesfully created'
        else
          flash.now[:error] = 'Create new store failed'
        end
      }
    end
  end

  def edit
    @store = Store.friendly.find(params[:id])
  end

  def update
    @store = Store.friendly.find(params[:id])
    @updated = @store.update_attributes(store_params)
    respond_to do |f|
      f.html {redirect_to edit_admin_store_path(@store)}
      f.js {
      	if @updated
        	flash.now[:notice] = 'Succesfully updated'
        else
        	flash.now[:error] = 'Update failed'
        end
      }
    end
  end

  def destroy
    @store = Store.friendly.find(params[:id])
    @store.destroy
    redirect_to :back  
  end

  private
  def store_params
    params.require(:store).permit(:name, :address, :phone_number, :password)
  end
end

app/controllers/device/home_controller.rb
class Device::HomeController < ApplicationController
  
  def index

  end

  def buy

  end

  def bitbil

  end

  def store

  end

  def charge

  end

  def verify

  end
end

app/controllers/device/stores_controller.rb
class Device::StoresController < ApplicationController
	before_action :define_store
	before_action :checking_store_authentication, only: [:verify, :verifying, :charge, :charging]

	def show
		reset_session
	end

	def buy
	end

	def buying
		user = User.find_by_phone_number(params[:screen_id])
		if user.present?
			set_login_history(user)
			session[:user_buying] = user.id
			trade = user.trades.open_or_buying.first
			if trade
				trade.update_attributes status: 'buying_btc', location_to_pay: @store.name
				session[:trade_id] = trade.id
				redirect_to store_device_store_path(@store)
			else
				flash.now[:error] = "You have not trading for now."
				render :buy
			end

		else
			flash.now[:error] = "User not found"
			render :buy
		end
	end

	def store
    if session[:user_buying].nil? || session[:trade_id].nil?
      redirect_to buy_device_store_path and return
    end
	end

	def storing
		authenticate = @store.authenticate(params[:screen_id])
		if authenticate
			session[:store_authenticate] = true
			redirect_to verify_device_store_path
		else
			flash.now[:error] = "Store password invalid"
			render :store
		end
	end

	def verify  	
		@user = User.find_by_id(session[:user_buying])
	end

	def verifying
		@trade = Trade.find_by_id(session[:trade_id])
		if @trade
			redirect_to charge_device_store_path(@store)
		else
			flash[:error] = "Trading not found"
			render :verifying
		end
	end

	def charge
		@trade = Trade.find_by_id(session[:trade_id])
	end

	def charging
		@trade = Trade.find_by_id(session[:trade_id])
		@updated = @trade.update_attributes(status: 'withdraw_requested') if @trade
		if @updated
			reset_session
			redirect_to device_store_path, notice: "Trading has been completed."
		end
	end

	private
	def checking_store_authentication
		unless session[:store_authenticate].eql?(true)
			redirect_to device_store_path, notice: 'Need to store authenticated' and return
		end
	end

	def reset_session
		session[:user_buying] = nil
		session[:trade_id] = nil
		session[:store_authenticate] = nil
	end

	def define_store
		@store = Store.friendly.find(params[:id])
	end
end

app/views/device/stores/_button_form.html.erb
<%= render "shared/messages" %>
<div class="form-group">
	<input name="screen_id" id="screen" type="text" class="form-control radius"></input>
</div>
<div class="clearfix"></div>
<div class="col-md-4">
	<%= link_to "1", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "2", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "3", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "4", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "5", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "6", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "7", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "8", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "9", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "DELETE", "#", class: "btn-number btn-delete" %>
</div>
<div class="col-md-4">
	<%= link_to "0", "#", class: "btn-number" %>
</div>
<div class="col-md-4">
	<%= link_to "ENTER", "javascript:void(0)", class: "btn-number enter", onclick: "$(this).parents('form').submit();" %>
</div>

app/views/device/stores/buy.html.erb
<div class="container">
	<div class="col-md-3">
		<%= image_tag('logo.png', class: 'img-resposive left-logo') %>
	</div>
	<div class="clearfix"></div>
	<div class="box-device">
		<div class="col-md-4 col-md-offset-2">
			<h1 class='insert-cellphone'>Insert your cellphone</h1>
		</div>
		<div class="col-md-4 box-keypad">
      <%= form_tag buying_device_store_path(@store) do %>
        <%= render "button_form" %>
      <% end %>
		</div>
	</div>
</div>

app/views/device/stores/charge.html.erb
<div class="container">
	<div class="col-md-3">
		<%= image_tag('logo.png', class: 'img-resposive left-logo') %>
	</div>
	<div class="clearfix"></div>
	<div class="box-device">
	  <h1 class="text-center">Charge and secure the payment:</h1>
	  <div class="info-name text-center">$<%= @trade.usd_amount.to_f.scale_2 %></div>
	  <div class="clearfix"></div>
	  <%= form_tag charging_device_store_path(@store) do %>
		  <div class="col-md-4 col-md-offset-2 box-button">
	      <%= button_tag "No, Cancel", class: "btn btn-default btn-cancel radius", onclick: "window.location='/device/stores/#{@store.friendly_id}" %>
		  </div>
		  <div class="col-md-4 box-button">
	      <%= button_tag "Yes, It secured", class: "btn btn-primary radius", onclick: "$(this).parents('form').submit()" %>
		  </div>
	  <% end %>
	</div>
</div>

app/views/device/stores/show.html.erb
<div class="container">
  <div class="box-device text-center">
    <%= image_tag('logo.png', class: 'logo') %>
    <h1>Welcome to BitBillers Kiosk</h1>
    <%= render "shared/messages" %>
    <%= button_tag "BUY BITCOIN", class: 'btn btn-primary radius btn-lg buy-btn', onclick: "window.location='/device/stores/#{@store.friendly_id}/buy'" %>
  </div>
</div>

app/views/device/stores/store.html.erb
<div class="container">
	<div class="col-md-3">
		<%= image_tag('logo.png', class: 'img-resposive left-logo') %>
	</div>
	<div class="clearfix"></div>
	<div class="box-device">
		<div class="col-md-4 col-md-offset-2 store">

			<h1 class='insert-cellphone'>Insert Store Password</h1>
		</div>
		<div class="col-md-4 box-keypad">
			<%= form_tag storing_device_store_path(@store) do %>
        <%= render "button_form" %>
      <% end %>
		</div>
	</div>
</div>

app/views/device/stores/verify.html.erb
<div class="container">
	<div class="col-md-3">
		<%= image_tag('logo.png', class: 'img-resposive left-logo') %>
	</div>
	<div class="clearfix"></div>
	<div class="box-device">
	  <h1 class="text-center">Request Customer ID<br/>verify if is:</h1>
	  <div class="info-name text-center"><%= @user.email %></div>
	  <div class="clearfix"></div>
	  <%= form_tag verifying_device_store_path(@store) do %>
	    <%= render "shared/messages" %>
		  <div class="col-md-4 col-md-offset-2 box-button">
	      <%= button_tag "No, Cancel", class: "btn btn-default btn-cancel radius", onclick: "window.location='/device/stores/#{@store.friendly_id}'" %>
		  </div>
		  <div class="col-md-4 box-button">
	      <%= button_tag "Yes, It is", class: "btn btn-primary radius", onclick: "$(this).parents('form').submit();" %>
		  </div>
	  <% end %>
	</div>
</div>