config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "login" => "users/sessions#new", :as => :signin_user
    post "login" => "users/sessions#create", :as => :signin_user_create
    get "logout" => "users/sessions#destroy", :as => :signout_user
  end

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }
  resources :users

  root "home#index"

  get "markets" => "markets#index", as: :markets

  namespace :admin do
    root "trades#new"
    get 'settings' => 'configurations#edit', as: :settings
    patch 'update_setting' => 'configurations#update', as: :update_setting

    resources :trades do
      member do
        get :release
        patch :released
        get :status
        patch :change_status
      end
    end
    resources :dashboards, only: [:index]
    resources :users do
      member do
        get :status
        patch :change_status
        get :trades
        get :login_histories
      end
    end
    resources :stores
  end

  namespace :device do
    resources :stores, only: [:show] do
      member do
        get :buy
        post :buying
        get :store
        post :storing
        get :verify
        post :verifying
        get :charge
        post :charging
      end
    end
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  extend FriendlyId
  require 'bcrypt'
  friendly_id :name, use: :slugged
  attr_accessor :password, :password_hash

  validates_presence_of :name
  validates_uniqueness_of :name, :slug
  validate :password_format

  before_save :encryption_password

  def password_format
    if !self.new_record? && !password.present?
      return
    end
    if self.new_record? && !password.present?
      self.errors.add :password, 'Cant be blank.'
    end
    unless password.numeric?
      self.errors.add :password, 'Only numeric allowed.'
    end
  end

  def encryption_password
    if !self.new_record? && !password.present?
      return
    end
    self.password_hash = self.password
  end

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

  def password_hash
    if self.encrypted_password
      BCrypt::Password.new(self.encrypted_password)
    end
  end

  def password_hash=(new_password)
    @password_hash = BCrypt::Password.create(new_password)
    self.encrypted_password = @password_hash
  end

  def authenticate(pass)
    self.password_hash == pass
  end

  def url
    host = if Rails.env.eql?('development')
      "http://localhost:3000/device/stores/#{self.friendly_id}"
    else
      "http://104.236.38.53/device/stores/#{self.friendly_id}"
    end
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::ApplicationController

  def index
    @stores = Store.order(:name).page(params[:page]).per(25)
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    @created = @store.save
    respond_to do |f|
      f.html{redirect_to new_admin_store_path}
      f.js{
        if @created
          flash.now[:notice] = 'Succesfully created'
        else
          flash.now[:error] = 'Create new store failed'
        end
      }
    end
  end

  def edit
    @store = Store.friendly.find(params[:id])
  end

  def update
    @store = Store.friendly.find(params[:id])
    @updated = @store.update_attributes(store_params)
    respond_to do |f|
      f.html {redirect_to edit_admin_store_path(@store)}
      f.js {
      	if @updated
        	flash.now[:notice] = 'Succesfully updated'
        else
        	flash.now[:error] = 'Update failed'
        end
      }
    end
  end

  def destroy
    @store = Store.friendly.find(params[:id])
    @store.destroy
    redirect_to :back  
  end

  private
  def store_params
    params.require(:store).permit(:name, :address, :phone_number, :password)
  end
end

app/controllers/device/stores_controller.rb
class Device::StoresController < ApplicationController
	before_action :define_store
	before_action :checking_store_authentication, only: [:verify, :verifying, :charge, :charging]

	def show
		reset_session
	end

	def buy
	end

	def buying
		user = User.find_by_phone_number(params[:screen_id])
		if user.present?
			set_login_history(user)
			session[:user_buying] = user.id
			trade = user.trades.open_or_buying.first
			if trade
				trade.update_attributes status: 'buying_btc', location_to_pay: @store.name
				session[:trade_id] = trade.id
				redirect_to store_device_store_path(@store)
			else
				flash.now[:error] = "You have not trading for now."
				render :buy
			end

		else
			flash.now[:error] = "User not found"
			render :buy
		end
	end

	def store
    if session[:user_buying].nil? || session[:trade_id].nil?
      redirect_to buy_device_store_path and return
    end
	end

	def storing
		authenticate = @store.authenticate(params[:screen_id])
		if authenticate
			session[:store_authenticate] = true
			redirect_to verify_device_store_path
		else
			flash.now[:error] = "Store password invalid"
			render :store
		end
	end

	def verify  	
		@user = User.find_by_id(session[:user_buying])
	end

	def verifying
		@trade = Trade.find_by_id(session[:trade_id])
		if @trade
			redirect_to charge_device_store_path(@store)
		else
			flash[:error] = "Trading not found"
			render :verifying
		end
	end

	def charge
		@trade = Trade.find_by_id(session[:trade_id])
	end

	def charging
		@trade = Trade.find_by_id(session[:trade_id])
		@updated = @trade.update_attributes(status: 'withdraw_requested') if @trade
		if @updated
			reset_session
			redirect_to device_store_path, notice: "Trading has been completed."
		end
	end

	private
	def checking_store_authentication
		unless session[:store_authenticate].eql?(true)
			redirect_to device_store_path, notice: 'Need to store authenticated' and return
		end
	end

	def reset_session
		session[:user_buying] = nil
		session[:trade_id] = nil
		session[:store_authenticate] = nil
	end

	def define_store
		@store = Store.friendly.find(params[:id])
	end
end

app/views/admin/stores/_form.html.erb
<%= form_for @store, url: @store.new_record? ? admin_stores_path : admin_store_path, remote: true, method: @store.new_record? ? :post : :patch do |f| %>
  <%= render 'shared/messages' %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <small class="label label-danger"><%= @store.errors[:name].join(", ") %></small>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <small>Only numeric format allowed.</small>
    <%- unless f.object.new_record? %>
      <small>Leave it blank if you dont want to change store password</small>
    <% end %>
    <small class="label label-danger"><%= @store.errors[:password].join(", ") %></small>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
    <small class="label label-danger"><%= @store.errors[:address].join(", ") %></small>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
    <small class="label label-danger"><%= @store.errors[:phone_number].join(", ") %></small>
  </div>
  <%= f.submit "Save", class: 'btn btn-primary', data: {disable_with: 'saving...'} %>
<% end %> 

app/views/admin/stores/_row.html.erb
	<td>
		<%= store.name %>
	</td>
	<td><%= store.address %></td>
	<td><%= store.phone_number %></td>
	<td><%= link_to store.url, store.url, target: 'blank' %></td>
	<td>
		<%= link_to "javascript:void(0)", onclick: "openModalSmall('#{edit_admin_store_path(store, popup: true)}')" do %>
		<i class="fa fa-pencil"></i>
		<% end %>
		<%= link_to admin_store_path(store), data: {confirm: 'are you sure?'}, method: :delete do %>
		<i class="fa fa-trash"></i>
		<% end %>
	</td>

app/views/admin/stores/create.js.erb
<%- if @created %>
  $("#store-table tbody").prepend("<tr id='store-<%=@store.id%>'><%= escape_javascript(render partial: 'row', locals: {store: @store}) %></tr>");
  $("#window-modal-small").modal('hide');
<% else %>
	html = '<%= escape_javascript(render "form") %>';
	$("#window-modal-small .modal-content .form-store").html(html);
<% end %>

app/views/admin/stores/destroy.js.erb
$("#store-<%= @store.id%>").remove();

app/views/admin/stores/edit.html.erb
<h1>Edit Store</h1>
<div class="form-store">
  <%= render "form" %>
</div>

app/views/admin/stores/index.html.erb
<h1>Store</h1>
<%= link_to "javascript:void(0)", class: 'btn btn-primary', onclick: "openModalSmall('#{new_admin_store_path(popup: true)}')" do %>
  <i class="fa fa-plus"></i> Add new Store
<% end %>
<hr/>
<div class="table-responsive">
	<table class='table' id='store-table'>
		<thead>
			<tr>
				<th>Name</th>
				<th>Address</th>
				<th>Phone Number</th>
				<th>URL</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<%- @stores.each do |store| %>
        <tr id="store-<%= store.id %>">
          <%= render partial: "row", locals: {store: store} %>
        </tr>
			<% end %>
			<tr>
        <td colspan="16">
          <%= paginate @stores %>
        </td>
			</tr>
		</tbody>
	</table>
</div>

app/views/admin/stores/new.html.erb
<h1>Create new store</h1>
<div class='form-store'>
  <%= render "form" %>
</div>

app/views/admin/stores/update.js.erb
html = '<%= escape_javascript(render "form") %>';
$("#window-modal-small .modal-content .form-store").html(html);
$("#store-<%= @store.id %>").html("<%= escape_javascript(render partial: 'row', locals: {store: @store}) %>");