config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "login" => "users/sessions#new", :as => :signin_user
    post "login" => "users/sessions#create", :as => :signin_user_create
    get "logout" => "users/sessions#destroy", :as => :signout_user
  end

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }
  resources :users

  root "home#index"

  get "markets" => "markets#index", as: :markets

  namespace :admin do
    root "trades#new"
    get 'settings' => 'configurations#edit', as: :settings
    patch 'update_setting' => 'configurations#update', as: :update_setting

    resources :trades do
      member do
        get :release
        patch :released
        get :status
        patch :change_status
      end
    end
    resources :dashboards, only: [:index]
    resources :users do
      member do
        get :status
        patch :change_status
        get :trades
        get :login_histories
      end
    end
    resources :stores
  end

  namespace :device do
    resources :stores, only: [:show] do
      member do
        get :buy
        post :buying
        get :store
        post :storing
        get :verify
        post :verifying
        get :charge
        post :charging
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles, join_table: 'users_roles'

  has_many :trades
  has_many :login_histories, dependent: :destroy
  has_one  :address, dependent: :destroy

  scope :members, -> {joins(:roles).where(:"roles.name" => 'member')}
  scope :admin, -> {joins(:roles).where(:"roles.name" => 'admin')}

  after_create :set_member, :generate_sms_code
 
  validates_presence_of :first_name, :last_name, :phone_number
  validates_uniqueness_of :phone_number

  accepts_nested_attributes_for :address

  def is_admin?
    roles.map(&:name).include?('admin')
  end

  def is_member?
    roles.map(&:name).include?('member')
  end

  def set_member
    self.role_ids = Role.find_by_name('member').id
  end

  def self.confirmed_count
    members.where(status: 'confirmed').count
  end

  def self.unconfirmed_count
    members.where(status: 'unconfirmed').count
  end

  def self.locked_count
    members.where(status: 'locked').count
  end

  def self.members_count
    members.count
  end

  def total_purchases
    trades.sum(:usd_amount).to_f.scale_2
  end

  def last_sign_in
    login_histories.last
  end

  def address_complete
    [address.address, address.city, address.state, address.zip_code, address.country].join(", ") rescue "-"
  end

  def generate_sms_code
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    string = (0...4).map { o[rand(o.length)] }.join
    self.sms_code = string
    save
  end

  def self.status_arr
    [
      ['Confirmed', 'confirmed'],
      ['UnConfirmed', 'unconfirmed'],
      ['Locked', 'locked']
    ]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  def index  	
  	@users = User.members.order(created_at: :desc)
  	if params[:status].present?
      @users.where(status: params[:status])
  	end
  	@users = @users.page(params[:page]).per(25)
  end

  def new
    @user = User.new
    @user.build_address
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:notice] = "Successfully created."
    end
    respond_to do |f|
      f.html{}
      f.js{}
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy if @user
    redirect_to :back
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(user_params)
      flash.now[:notice] = "Successfully updated."
    end
    respond_to do |f|
      f.html {}
      f.js {}
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
    respond_to do |f|
      f.html {}
      f.js {}
    end
  end

  def trades
    @user = User.find_by_id(params[:id])
    @trades = @user.trades.order(created_at: :desc).page(params[:page]).per(20)
    respond_to do |f|
      f.html {}
      f.js {}
    end
  end

  def login_histories
    @user = User.find_by_id(params[:id])
    @login_histories = @user.login_histories.order(created_at: :desc).page(params[:page]).per(20)
    respond_to do |f|
      f.html {}
      f.js {}
    end
  end

  def status
    @user = User.find_by_id(params[:id])
  end

  def change_status
    @user = User.find_by_id(params[:id])
    @state = @user.update_attributes(status: params[:user][:status])
  end

  private
  def user_params
    if !params[:user][:password].present? && @user
      params[:user].delete(:password)
    end
    params.require(:user).permit(:password_confirmation, :password, :email, :phone_number, :first_name, :last_name, address_attributes: [:country, :state, :city, :address, :zip_code])
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  def new
    build_resource({})
    set_minimum_password_length
    resource.address = resource.address.nil? ? resource.build_address : resource.address   
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.address = resource.address.nil? ? resource.build_address : resource.address   
    resource.save
    yield resource if block_given?
    if resource.persisted?
      resource.set_member
      resource.generate_sms_code
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    resource.build_address if resource.address.nil?
    super
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
    resource_updated = resource.update_attributes(custom_update)
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, bypass: true
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :phone_number, :first_name, :last_name, address_attributes: [:country, :state, :city, :address, :zip_code])
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    # devise_parameter_sanitizer.for(:account_update) do |user_params|
    #   user_params.permit(:email, :phone_number, :first_name, :last_name, address_attributes: [:country, :state, :city, :address, :zip_code])
    # end
  end

  def custom_update
    if !params[:user][:password].present?
      params[:user].delete(:password)
    end
    params.require(:user).permit(:password, :email, :phone_number, :first_name, :last_name, address_attributes: [:country, :state, :city, :address, :zip_code])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/views/admin/users/_link_status.html.erb
		<%= link_to "javascript:void(0)", onclick: "openModalSmall('#{status_admin_user_path(user.id, popup: true)}')" do %>
  		<span class="<%= user_get_status(user) %>"><%= user.status %></span>
		<% end %>

app/views/admin/users/_login_list.html.erb
<%- @login_histories.each do |login| %>
<tr>
	<td><%= login.created_at %></td>
	<td><%= login.ip_address %></td>
	<td><%= login.complete_name %></td>
	<td><%= login.agent_name %></td>
</tr>
<% end %>
<tr>
	<td colspan="4"><%= paginate @login_histories, remote: true %></td>
</tr>

app/views/admin/users/_row.html.erb
	<td>
		<%= user.id %>
	</td>
	<td>
		<%= user.created_at %>
	</td>
	<td>
		<%= user.last_sign_in.ip_address rescue '-' %>
	</td>
	<td>
		<%= user.last_sign_in.complete_name rescue '-' %>
	</td>
	<td>
		<%= user.email %>
	</td>
	<td>
		<%= user.phone_number %>
	</td>
	<td>
		<%= user.sms_verified ? 'Yes' : 'No' %>
	</td>
	<td>
		<%= user.id_verified ? 'Yes' : 'No' %>
	</td>
	<td>
		$ <%= user.total_purchases %>
	</td>
	<td>
		<%= link_to "Check", "javascript:void(0)", onclick: "openModal('#{trades_admin_user_path(user, popup: true)}')" %>
	</td>
	<td>
		<%= link_to "Check", "javascript:void(0)", onclick: "openModal('#{login_histories_admin_user_path(user, popup: true)}')" %>
	</td>
	<td><%= user.first_name %></td>
	<td><%= user.last_name %></td>
	<td><%= user.address_complete %></td>
	<td id="user-<%= user.id %>-status">
    <%= render partial: "link_status", locals: {user: user} %>
	</td>
	<td>
		<%= link_to "javascript:void(0)", onclick: "openModal('#{edit_admin_user_path(user, popup: true)}')" do %>
		<i class="fa fa-pencil"></i>
		<% end %>
		<%= link_to admin_user_path(user), data: {confirm: 'are you sure?'}, method: :delete do %>
		<i class="fa fa-trash"></i>
		<% end %>
	</td>

app/views/admin/users/_trade_list.html.erb
<%- @trades.each do |trade| %>
<tr>
	<td><%= trade.id %></td>
	<td><%= trade.created_at %></td>
	<td><%= trade.phone_number %></td>
	<td><%= trade.wallet %></td>
	<td><%= trade.usd_amount %></td>
	<td><%= trade.btc_amount %></td>
	<td><%= trade.location_to_pay %></td>
	<td>
	  <span class="<%= get_trade_status(trade.status) %>"><%= trade.status.humanize %></span>
  </td>
</tr>
<% end %>
<tr>
	<td colspan="8"><%= paginate @trades, remote: true %></td>
</tr>

app/views/admin/users/change_status.js.erb
$("#user-<%= @user.id %>-status").html("<%= escape_javascript(render partial: 'link_status', locals: {user: @user}) %>");
$("#window-modal-small").modal('hide');

app/views/admin/users/create.js.erb
<%- if @user.errors.empty? %>
  $("#window-modal").modal('hide');
  $("#user-table tbody").prepend("<tr id='user-<%= @user.id %>'><%= escape_javascript(render partial: 'row', locals: {user: @user}) %></tr>");
<% else %>
	html = '<%= escape_javascript(render "form") %>';
	$("#window-modal .modal-content").html(html);
<% end %>

app/views/admin/users/edit.html.erb
<%= render "form" %>

app/views/admin/users/edit.js.erb
html = '<%= escape_javascript(render "form") %>';
$("#window-modal .modal-content").html(html);

app/views/admin/users/index.html.erb
<h1>Users</h1>
<%= link_to "javascript:void(0)", class: 'btn btn-primary', onclick: "openModal('#{new_admin_user_path(popup: true)}')" do %>
  <i class="fa fa-plus"></i> Add new user
<% end %>
<hr/>
<ul class="nav nav-tabs">
	<li role="presentation" class="<%= 'active' if !params[:status].present? %>">
		<a href="/admin/users">All (<%= User.members_count %>)</a>
	</li>
	<li role="" class="<%= 'active' if params[:status].eql?('confirmed') %>"><a href="/admin/users?status=confirmed">Confirmed (<%= User.confirmed_count %>)</a></li>
	<li role="" class="<%= 'active' if params[:status].eql?('unconfirmed') %>"><a href="/admin/users?status=unconfirmed">Unconfirmed (<%= User.unconfirmed_count %>)</a></li>
	<li role="" class="<%= 'active' if params[:status].eql?('locked') %>"><a href="/admin/users?status=locked">Locked (<%= User.locked_count %>)</a></li>
</ul>
<div class="table-responsive">
	<table class='table' id='user-table'>
		<thead>
			<tr>
				<th>ID</th>
				<th>Date</th>
				<th>IP</th>
				<th>IP-Location</th>
				<th>email</th>
				<th>phone number</th>
				<th>SMS verified</th>
				<th>ID verified</th>
				<th>Total Purchases</th>
				<th>Trade List</th>
				<th>Login History</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Address</th>
				<th>Status</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<%- @users.each do |user| %>
        <tr id="user-<%= user.id %>">
          <%= render partial: "row", locals: {user: user} %>
        </tr>
			<% end %>
			<tr>
        <td colspan="16">
          <%= paginate @users %>
        </td>
			</tr>
		</tbody>
	</table>
</div>

app/views/admin/users/login_histories.html.erb
<h1>Login Histories for <%= @user.email %></h1>
<div class="table-responsive">
	<table class="table" id="histories">
		<thead>
			<tr>
				<td>Date</td>
				<td>IP Address</td>
				<td>IP Location</td>
				<td>User Agent</td>
			</tr>
		</thead>
		<tbody>
			<%= render "login_list" %>
		</tbody>
	</table>
</div>

app/views/admin/users/login_histories.js.erb
$("#histories tbody").html("<%= escape_javascript(render 'login_list') %>");

app/views/admin/users/new.html.erb
<%= render "form" %>

app/views/admin/users/status.html.erb
<div class="popup-content">
	<div class="popup-body">
		<%= form_for @user, url: change_status_admin_user_path(@user), method: :patch, remote: true do |f| %>
		<div class="form-group">
			<%= f.label :status %>
			<%= f.select :status, options_for_select(User.status_arr, selected: f.object.status), {}, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit "Change", class: 'btn btn-primary', data: {disable_with: 'Changin...'} %>
		</div>
		<% end %>
	</div>
</div>

app/views/admin/users/trades.html.erb
<h1>Trade List for <%= @user.email %></h1>
<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<td>ID</td>
				<td>Date</td>
				<td>Phone</td>
				<td>Wallet</td>
				<td>Amount USD</td>
				<td>Amount BTC</td>
				<td>Location To Pay</td>
				<td>Status</td>
			</tr>
		</thead>
		<tbody>
			<%= render "trade_list" %>
		</tbody>
	</table>
</div>